all:
	@echo -e "Run following:"
	@echo -e "\tsudo yum install acpi acpid"
	@echo -e "\tsudo crontab -e"
	@echo -e "\t\t@reboot echo disable > /sys/firmware/acpi/interrupts/gpe06"
	@echo -e "\tsudo reboot"
